name: Node.js CI

on:
  push:
    branches: [ frontend, main ]
  pull_request:
    branches: [ frontend, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongodb-version: ['4.0', '4.2', '4.4']
        redis-version: [4, 5]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }} 

    - name: Start Redis v${{ matrix.redis-version }}
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Installing Dependencies
      working-directory: backend
      run: npm install

    - name: Test backend
      working-directory: backend
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        DBHOST: ${{ secrets.DBHOST }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    - name: Test frontend
      working-directory: frontend
      run: |
        npm install --legacy-peer-deps
        npm test
    